# This is a basic workflow to help you get started with Actions

name: CMake CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run cmake program
      run: |
        sudo apt-get install libglew-dev libglfw3-dev
        mkdir cmake-build
        cmake -S . -B cmake-build
        cd cmake-build
        make
        mkdir out
        echo "./TutoCherno" > out/run.sh
        mv TutoCherno out
        chmod a+x out/run.sh
        chmod a+x out/TutoCherno
        
    - uses: actions/upload-artifact@v1
      with:
        name: TutoCherno
        path: cmake-build/out
